options = {
	["difficulty"] = {
		["avionicsLanguage"] = "english",
		["birds"] = 0,
		["cockpitLanguage"] = "english",
		["cockpitStatusBarAllowed"] = false,
		["cockpitVisualRM"] = false,
		["easyCommunication"] = true,
		["easyFlight"] = false,
		["easyRadar"] = false,
		["externalViews"] = true,
		["fuel"] = false,
		["geffect"] = "realistic",
		["hideStick"] = false,
		["iconsTheme"] = "nato",
		["immortal"] = false,
		["impostors"] = "",
		["labels"] = true,
		["map"] = true,
		["miniHUD"] = false,
		["optionsView"] = "optview_all",
		["padlock"] = true,
		["permitCrash"] = true,
		["radio"] = false,
		["reports"] = true,
		["setGlobal"] = true,
		["spectatorExternalViews"] = true,
		["tips"] = true,
		["units"] = "metric",
		["userSnapView"] = true,
		["weapons"] = false,
	},
	["graphics"] = {
		["DOF"] = 1,
		["HDR"] = 1,
		["LensEffects"] = 3,
		["MSAA"] = 2,
		["OculusRift"] = false,
		["TranspSSAA"] = false,
		["anisotropy"] = 2,
		["aspect"] = 1.7777777777778,
		["civTraffic"] = "high",
		["clouds"] = 2,
		["clutterMaxDistance"] = 1500,
		["cockpitShadows"] = true,
		["color"] = "32",
		["disableAero"] = false,
		["effects"] = 3,
		["flatTerrainShadows"] = 0,
		["fullScreen"] = false,
		["haze"] = 1,
		["heatBlr"] = 2,
		["height"] = 1080,
		["impostors"] = "enlarged",
		["lights"] = 2,
		["multiMonitorSetup"] = "1camera",
		["preloadRadius"] = 150000,
		["scenes"] = "high",
		["shadowTree"] = true,
		["shadows"] = 5,
		["sync"] = true,
		["terrainTextures"] = "max",
		["textures"] = 2,
		["treesVisibility"] = 25000,
		["visibRange"] = "Ultra",
		["water"] = 2,
		["width"] = 1920,
	},
	["miscellaneous"] = {
		["Coordinate_Display"] = "Lat Long",
		["F2_view_effects"] = 1,
		["accidental_failures"] = false,
		["f10_awacs"] = true,
		["f11_free_camera"] = true,
		["f5_nearest_ac"] = true,
		["force_feedback_enabled"] = true,
		["headmove"] = false,
		["show_pilot_body"] = false,
		["synchronize_controls"] = false,
	},
	["plugins"] = {
		["A-10C"] = {
			["CPLocalList"] = "default",
		},
		["CA"] = {
			["ground_aim_helper"] = true,
			["ground_automatic"] = true,
			["ground_platform_shake"] = false,
			["ground_target_info"] = true,
			["kompass_options"] = 1,
		},
		["F-86F"] = {
			["CPLocalList"] = "default",
			["gunCamera"] = 0,
			["landSeatAdjustF86"] = true,
		},
		["FC3"] = {
			["CPLocalList_A-10A"] = "default",
			["CPLocalList_F-15C"] = "default",
			["CPLocalList_MiG-29A"] = "default",
			["CPLocalList_MiG-29G"] = "default",
			["CPLocalList_MiG-29S"] = "default",
			["CPLocalList_Su-25"] = "default",
			["CPLocalList_Su-27"] = "chinese",
			["CPLocalList_Su-33"] = "default",
		},
		["Ka-50"] = {
			["CPLocalList"] = "english",
			["Ka50RudderTrimmer"] = false,
			["altTrimmingMethod"] = false,
		},
		["Mi-8MTV2"] = {
			["CPLocalList"] = "chinese",
			["Mi8AutopilotAdjustment"] = false,
			["Mi8FOV"] = 120,
			["Mi8RudderTrimmer"] = false,
			["altMi8TrimmingMethod"] = false,
			["controlHelperMi8"] = false,
			["weapTooltipsMi8"] = true,
		},
		["MiG-15bis"] = {
			["CPLocalList"] = "chinese",
			["aiHelper"] = false,
			["autoLeanToAimMiG15"] = true,
			["gunCamera"] = 0,
		},
		["MiG-21Bis"] = {
			["CustomCockpit"] = false,
			["Engine"] = false,
			["Freeze"] = false,
			["Reticle"] = false,
			["Shake"] = 100,
		},
		["Su-25T"] = {
			["CPLocalList"] = "default",
		},
		["TF-51D"] = {
			["CPLocalList"] = "default",
			["assistance"] = 100,
			["autoRudder"] = false,
		},
		["UH-1H"] = {
			["CPLocalList"] = "default",
			["UHRudderTrimmer"] = false,
			["UHTrackIRAiming"] = true,
			["altUHTrimmingMethod"] = false,
			["autoPilot"] = true,
			["weapTooltips"] = true,
		},
	},
	["sound"] = {
		["GBreathEffect"] = true,
		["cockpit"] = 0,
		["gui"] = 0,
		["headphones"] = 0,
		["hear_in_helmet"] = false,
		["music"] = -12,
		["radioSpeech"] = true,
		["subtitles"] = true,
		["volume"] = 0,
		["world"] = 0,
	},
	["views"] = {
		["cockpit"] = {
			["avionics"] = 4,
			["mirrors"] = false,
			["reflections"] = false,
			["russianHud"] = false,
		},
	},
}
