settings=
{
	["MaverickData"]=
	{
		["MavTime"]=
		{
			["M"]=0,
			["H"]=0,
			["S"]=0,
		},
		["MavPO"]=0,
		["AutoEOBearing"]=0,
		["AutoEORange"]=0,
		["MavWPT"]=0,
	},
	["ProfileParametrsByWpn"]=
	{
		[1]=
		{
			["type"]=
			{
				["level3"]=101,
				["level1"]=4,
				["level4"]=0,
				["level2"]=4,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
			},
		},
		[2]=
		{
			["type"]=
			{
				["level3"]=9,
				["level1"]=4,
				["level4"]=31,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[5]=
				{
					[0]=3,
				},
				[6]=
				{
					[1]=5,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=9,
					[6]=11,
					[7]=3,
					[8]=8,
					[0]=0,
				},
				[4]=
				{
					[1]=8,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=5,
					[6]=9,
					[7]=11,
					[8]=3,
					[9]=12,
					[0]=0,
				},
				[8]=
				{
					[0]=11,
				},
			},
			["nose_fuzes"]=
			{
				[1]=5,
				[2]=1,
				[3]=4,
				[4]=6,
				[5]=7,
				[6]=8,
				[0]=0,
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[5]=
				{
					[0]=3,
				},
				[6]=
				{
					[1]=7,
					[2]=3,
					[3]=5,
					[4]=9,
					[5]=11,
					[0]=1,
				},
				[4]=
				{
					[1]=7,
					[2]=9,
					[3]=1,
					[4]=6,
					[5]=5,
					[6]=8,
					[7]=10,
					[8]=3,
					[9]=11,
					[0]=0,
				},
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
				[1]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[4]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[5]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[6]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[7]=
				{
					[0]=1,
				},
				[8]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[0]=
				{
					[1]=1,
					[2]=4,
					[3]=6,
					[0]=5,
				},
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[2]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[3]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[4]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
				[5]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[6]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[7]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[8]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[9]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[3]=
		{
			["type"]=
			{
				["level3"]=9,
				["level1"]=4,
				["level4"]=33,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[5]=
				{
					[0]=3,
				},
				[6]=
				{
					[1]=5,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=9,
					[6]=11,
					[7]=3,
					[8]=8,
					[0]=0,
				},
				[4]=
				{
					[1]=8,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=5,
					[6]=9,
					[7]=11,
					[8]=3,
					[9]=12,
					[0]=0,
				},
				[8]=
				{
					[0]=11,
				},
			},
			["nose_fuzes"]=
			{
				[1]=5,
				[2]=1,
				[3]=4,
				[4]=6,
				[5]=7,
				[6]=8,
				[0]=0,
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[5]=
				{
					[0]=3,
				},
				[6]=
				{
					[1]=7,
					[2]=3,
					[3]=5,
					[4]=9,
					[5]=11,
					[0]=1,
				},
				[4]=
				{
					[1]=7,
					[2]=9,
					[3]=1,
					[4]=6,
					[5]=5,
					[6]=8,
					[7]=10,
					[8]=3,
					[9]=11,
					[0]=0,
				},
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
				[1]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[4]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[5]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[6]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[7]=
				{
					[0]=1,
				},
				[8]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[0]=
				{
					[1]=1,
					[2]=4,
					[3]=6,
					[0]=5,
				},
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[2]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[3]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[4]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
				[5]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[6]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[7]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[8]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[9]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[4]=
		{
			["type"]=
			{
				["level3"]=38,
				["level1"]=4,
				["level4"]=35,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=12,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="HOF:",
				},
				[2]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[3]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[4]=
				{
					["ParamType"]=11,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FUNC TIME:",
				},
				[5]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[6]=
				{
					["ParamType"]=10,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FZU39:",
				},
				[7]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[8]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[9]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[10]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[5]=
		{
			["type"]=
			{
				["level3"]=36,
				["level1"]=4,
				["level4"]=36,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[4]=
				{
					[1]=8,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=5,
					[6]=9,
					[7]=11,
					[8]=3,
					[9]=12,
					[0]=0,
				},
				[9]=
				{
					[1]=4,
					[2]=9,
					[3]=2,
					[4]=5,
					[5]=8,
					[6]=12,
					[7]=3,
					[8]=7,
					[0]=1,
				},
			},
			["nose_fuzes"]=
			{
				[1]=0,
				[2]=1,
				[3]=9,
				[0]=4,
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
				[8]=18,
				[9]=19,
				[10]=20,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[6]=
				{
					[1]=7,
					[2]=3,
					[3]=5,
					[4]=9,
					[5]=11,
					[0]=1,
				},
				[4]=
				{
					[1]=7,
					[2]=9,
					[3]=1,
					[4]=6,
					[5]=5,
					[6]=8,
					[7]=10,
					[8]=3,
					[9]=11,
					[0]=0,
				},
				[10]=
				{
					[1]=4,
					[2]=8,
					[3]=2,
					[4]=5,
					[5]=7,
					[6]=11,
					[7]=3,
					[8]=6,
					[0]=1,
				},
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=1,
					[3]=4,
					[4]=10,
					[0]=0,
				},
				[0]=
				{
					[1]=1,
					[2]=4,
					[3]=10,
					[0]=6,
				},
				[4]=
				{
					[1]=6,
					[2]=1,
					[3]=4,
					[4]=10,
					[0]=0,
				},
				[9]=
				{
					[1]=6,
					[2]=1,
					[3]=4,
					[4]=10,
					[0]=0,
				},
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[2]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[3]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[4]=
				{
					["ParamType"]=25,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LASER CODE:",
				},
				[5]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[6]=
				{
					["ParamType"]=18,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="AUTO LASE:",
				},
				[7]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[8]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
				[9]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[10]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[11]=
				{
					["ParamType"]=19,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="SOLUTION:",
				},
				[12]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[13]=
				{
					["ParamType"]=20,
					["Format"]="%d SEC",
					["IsUnderline"]=1,
					["StringName"]="LASE TIME:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[6]=
		{
			["type"]=
			{
				["level3"]=36,
				["level1"]=4,
				["level4"]=38,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[4]=
				{
					[1]=8,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=5,
					[6]=9,
					[7]=11,
					[8]=3,
					[9]=12,
					[0]=0,
				},
				[9]=
				{
					[1]=4,
					[2]=9,
					[3]=2,
					[4]=5,
					[5]=8,
					[6]=12,
					[7]=3,
					[8]=7,
					[0]=1,
				},
			},
			["nose_fuzes"]=
			{
				[1]=0,
				[2]=1,
				[3]=9,
				[0]=4,
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
				[8]=18,
				[9]=19,
				[10]=20,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[6]=
				{
					[1]=7,
					[2]=3,
					[3]=5,
					[4]=9,
					[5]=11,
					[0]=1,
				},
				[4]=
				{
					[1]=7,
					[2]=9,
					[3]=1,
					[4]=6,
					[5]=5,
					[6]=8,
					[7]=10,
					[8]=3,
					[9]=11,
					[0]=0,
				},
				[10]=
				{
					[1]=4,
					[2]=8,
					[3]=2,
					[4]=5,
					[5]=7,
					[6]=11,
					[7]=3,
					[8]=6,
					[0]=1,
				},
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=1,
					[3]=4,
					[4]=10,
					[0]=0,
				},
				[0]=
				{
					[1]=1,
					[2]=4,
					[3]=10,
					[0]=6,
				},
				[4]=
				{
					[1]=6,
					[2]=1,
					[3]=4,
					[4]=10,
					[0]=0,
				},
				[9]=
				{
					[1]=6,
					[2]=1,
					[3]=4,
					[4]=10,
					[0]=0,
				},
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[2]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[3]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[4]=
				{
					["ParamType"]=25,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LASER CODE:",
				},
				[5]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[6]=
				{
					["ParamType"]=18,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="AUTO LASE:",
				},
				[7]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[8]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
				[9]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[10]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[11]=
				{
					["ParamType"]=19,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="SOLUTION:",
				},
				[12]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[13]=
				{
					["ParamType"]=20,
					["Format"]="%d SEC",
					["IsUnderline"]=1,
					["StringName"]="LASE TIME:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[7]=
		{
			["type"]=
			{
				["level3"]=8,
				["level1"]=4,
				["level4"]=61,
				["level2"]=4,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
			},
		},
		[8]=
		{
			["type"]=
			{
				["level3"]=49,
				["level1"]=4,
				["level4"]=64,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=14,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="SUU25 MNT:",
				},
				[2]=
				{
					["ParamType"]=13,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FF DIST:",
				},
				[0]=
				{
					["ParamType"]=14,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="H OVR TGT:",
				},
			},
		},
		[9]=
		{
			["type"]=
			{
				["level3"]=9,
				["level1"]=4,
				["level4"]=69,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=16,
				[8]=2,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[2]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[3]=
				{
					["ParamType"]=15,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="SERIES:",
				},
				[4]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[5]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[6]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[7]=
				{
					["ParamType"]=16,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="MIN TOF:",
				},
				[8]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[10]=
		{
			["type"]=
			{
				["level3"]=8,
				["level1"]=4,
				["level4"]=70,
				["level2"]=4,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
			},
		},
		[11]=
		{
			["type"]=
			{
				["level3"]=9,
				["level1"]=4,
				["level4"]=70,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[5]=
				{
					[0]=3,
				},
				[6]=
				{
					[1]=5,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=9,
					[6]=11,
					[7]=3,
					[8]=8,
					[0]=0,
				},
				[4]=
				{
					[1]=8,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=5,
					[6]=9,
					[7]=11,
					[8]=3,
					[9]=12,
					[0]=0,
				},
				[8]=
				{
					[1]=5,
					[2]=3,
					[3]=4,
					[4]=6,
					[5]=7,
					[6]=11,
					[0]=2,
				},
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[5]=
				{
					[0]=3,
				},
				[6]=
				{
					[1]=7,
					[2]=3,
					[3]=5,
					[4]=9,
					[5]=11,
					[0]=1,
				},
				[4]=
				{
					[1]=7,
					[2]=9,
					[3]=1,
					[4]=6,
					[5]=5,
					[6]=8,
					[7]=10,
					[8]=3,
					[9]=11,
					[0]=0,
				},
			},
			["nose_fuzes_by_config"]=
			{
				[0]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[5]=7,
					[6]=8,
					[0]=0,
				},
			},
			["tail_fuze_by_config_fuze"]=
			{
				[0]=
				{
					[0]=
					{
						[1]=5,
						[2]=1,
						[3]=4,
						[4]=6,
						[0]=0,
					},
				},
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[2]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[3]=
				{
					["ParamType"]=15,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="SERIES:",
				},
				[4]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[5]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[6]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[7]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[8]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
				[9]=
				{
					["ParamType"]=17,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="CONFIG:",
				},
				[10]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[11]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[12]=
		{
			["type"]=
			{
				["level3"]=9,
				["level1"]=4,
				["level4"]=71,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[2]=
				{
					[1]=0,
					[2]=28,
					[3]=2,
					[0]=1,
				},
				[3]=
				{
					[1]=25,
					[2]=22,
					[3]=26,
					[4]=20,
					[5]=15,
					[6]=18,
					[7]=23,
					[8]=17,
					[9]=27,
					[10]=24,
					[11]=14,
					[12]=21,
					[13]=19,
					[14]=16,
					[0]=13,
				},
				[6]=
				{
					[1]=5,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=9,
					[6]=11,
					[7]=3,
					[8]=8,
					[0]=0,
				},
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=21,
				[8]=22,
				[9]=2,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[2]=
				{
					[1]=0,
					[2]=27,
					[3]=2,
					[0]=1,
				},
				[3]=
				{
					[1]=24,
					[2]=21,
					[3]=25,
					[4]=19,
					[5]=14,
					[6]=17,
					[7]=22,
					[8]=16,
					[9]=26,
					[10]=23,
					[11]=13,
					[12]=20,
					[13]=18,
					[14]=15,
					[0]=12,
				},
				[11]=
				{
					[1]=38,
					[2]=36,
					[3]=39,
					[4]=34,
					[5]=30,
					[6]=33,
					[7]=2,
					[8]=32,
					[9]=3,
					[10]=37,
					[11]=29,
					[12]=35,
					[13]=1,
					[14]=31,
					[0]=28,
				},
				[6]=
				{
					[1]=7,
					[2]=3,
					[3]=5,
					[4]=9,
					[5]=11,
					[0]=1,
				},
				[12]=
				{
					[1]=0,
					[2]=28,
					[3]=6,
					[4]=44,
					[5]=31,
					[6]=43,
					[7]=29,
					[8]=45,
					[9]=42,
					[10]=30,
					[11]=32,
					[0]=40,
				},
			},
			["nose_fuzes_by_config"]=
			{
				[2]=
				{
					[1]=0,
					[2]=2,
					[3]=7,
					[0]=6,
				},
				[3]=
				{
					[1]=0,
					[2]=1,
					[3]=7,
					[0]=6,
				},
				[4]=
				{
					[1]=0,
					[2]=3,
					[3]=7,
					[0]=6,
				},
				[5]=
				{
					[0]=6,
				},
				[6]=
				{
					[0]=6,
				},
			},
			["tail_fuze_by_config_fuze"]=
			{
				[2]=
				{
					[2]=
					{
						[0]=2,
					},
				},
				[3]=
				{
					[3]=
					{
						[0]=1,
					},
				},
				[4]=
				{
					[4]=
					{
						[0]=3,
					},
				},
				[5]=
				{
					[5]=
					{
						[0]=3,
					},
				},
				[6]=
				{
					[6]=
					{
						[0]=2,
					},
				},
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
				[2]=
				{
					["ParamType"]=22,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES LD TOF:",
				},
				[3]=
				{
					["ParamType"]=15,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="SERIES:",
				},
				[4]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[5]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[6]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[7]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[8]=
				{
					["ParamType"]=21,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES HD TOF:",
				},
				[9]=
				{
					["ParamType"]=17,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="CONFIG:",
				},
				[10]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[11]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[12]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[13]=
		{
			["type"]=
			{
				["level3"]=36,
				["level1"]=4,
				["level4"]=72,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[4]=
				{
					[1]=7,
					[2]=1,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=0,
				},
				[9]=
				{
					[1]=4,
					[2]=9,
					[3]=2,
					[4]=5,
					[5]=8,
					[6]=12,
					[7]=3,
					[8]=7,
					[0]=1,
				},
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
				[8]=18,
				[9]=19,
				[10]=20,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[6]=
				{
					[1]=7,
					[2]=3,
					[3]=5,
					[4]=9,
					[5]=11,
					[0]=1,
				},
				[4]=
				{
					[1]=6,
					[2]=1,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=0,
				},
				[10]=
				{
					[1]=4,
					[2]=8,
					[3]=2,
					[4]=5,
					[5]=7,
					[6]=11,
					[7]=3,
					[8]=6,
					[0]=1,
				},
			},
			["nose_fuzes_by_config"]=
			{
				[1]=
				{
					[1]=0,
					[2]=1,
					[3]=9,
					[0]=4,
				},
			},
			["tail_fuze_by_config_fuze"]=
			{
				[1]=
				{
					[1]=
					{
						[1]=6,
						[2]=1,
						[3]=4,
						[4]=10,
						[0]=0,
					},
				},
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[2]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[3]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[4]=
				{
					["ParamType"]=25,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LASER CODE:",
				},
				[5]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[6]=
				{
					["ParamType"]=18,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="AUTO LASE:",
				},
				[7]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[8]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
				[9]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[10]=
				{
					["ParamType"]=17,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="CONFIG:",
				},
				[11]=
				{
					["ParamType"]=19,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="SOLUTION:",
				},
				[12]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[13]=
				{
					["ParamType"]=20,
					["Format"]="%d SEC",
					["IsUnderline"]=1,
					["StringName"]="LASE TIME:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[14]=
		{
			["type"]=
			{
				["level3"]=9,
				["level1"]=4,
				["level4"]=73,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[5]=
				{
					[0]=3,
				},
				[6]=
				{
					[1]=5,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=9,
					[6]=11,
					[7]=3,
					[8]=8,
					[0]=0,
				},
				[4]=
				{
					[1]=8,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=5,
					[6]=9,
					[7]=11,
					[8]=3,
					[9]=12,
					[0]=0,
				},
				[8]=
				{
					[1]=5,
					[2]=3,
					[3]=4,
					[4]=6,
					[5]=7,
					[6]=11,
					[0]=2,
				},
			},
			["nose_fuzes"]=
			{
				[1]=5,
				[2]=1,
				[3]=4,
				[4]=6,
				[5]=7,
				[6]=8,
				[0]=0,
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[5]=
				{
					[0]=3,
				},
				[6]=
				{
					[1]=7,
					[2]=3,
					[3]=5,
					[4]=9,
					[5]=11,
					[0]=1,
				},
				[4]=
				{
					[1]=7,
					[2]=9,
					[3]=1,
					[4]=6,
					[5]=5,
					[6]=8,
					[7]=10,
					[8]=3,
					[9]=11,
					[0]=0,
				},
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
				[1]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[4]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[5]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[6]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[7]=
				{
					[0]=1,
				},
				[8]=
				{
					[1]=5,
					[2]=1,
					[3]=4,
					[4]=6,
					[0]=0,
				},
				[0]=
				{
					[1]=1,
					[2]=4,
					[3]=6,
					[0]=5,
				},
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[2]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[3]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[4]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
				[5]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[6]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[7]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[8]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[9]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[15]=
		{
			["type"]=
			{
				["level3"]=36,
				["level1"]=4,
				["level4"]=74,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[4]=
				{
					[1]=8,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=5,
					[6]=9,
					[7]=11,
					[8]=3,
					[9]=12,
					[0]=0,
				},
				[9]=
				{
					[1]=4,
					[2]=9,
					[3]=2,
					[4]=5,
					[5]=8,
					[6]=12,
					[7]=3,
					[8]=7,
					[0]=1,
				},
			},
			["nose_fuzes"]=
			{
				[1]=0,
				[2]=1,
				[3]=9,
				[0]=4,
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
				[8]=18,
				[9]=19,
				[10]=20,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[6]=
				{
					[1]=7,
					[2]=3,
					[3]=5,
					[4]=9,
					[5]=11,
					[0]=1,
				},
				[4]=
				{
					[1]=7,
					[2]=9,
					[3]=1,
					[4]=6,
					[5]=5,
					[6]=8,
					[7]=10,
					[8]=3,
					[9]=11,
					[0]=0,
				},
				[10]=
				{
					[1]=4,
					[2]=8,
					[3]=2,
					[4]=5,
					[5]=7,
					[6]=11,
					[7]=3,
					[8]=6,
					[0]=1,
				},
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=1,
					[3]=4,
					[4]=10,
					[0]=0,
				},
				[0]=
				{
					[1]=1,
					[2]=4,
					[3]=10,
					[0]=6,
				},
				[4]=
				{
					[1]=6,
					[2]=1,
					[3]=4,
					[4]=10,
					[0]=0,
				},
				[9]=
				{
					[1]=6,
					[2]=1,
					[3]=4,
					[4]=10,
					[0]=0,
				},
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[2]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[3]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[4]=
				{
					["ParamType"]=25,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LASER CODE:",
				},
				[5]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[6]=
				{
					["ParamType"]=18,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="AUTO LASE:",
				},
				[7]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[8]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
				[9]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[10]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[11]=
				{
					["ParamType"]=19,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="SOLUTION:",
				},
				[12]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[13]=
				{
					["ParamType"]=20,
					["Format"]="%d SEC",
					["IsUnderline"]=1,
					["StringName"]="LASE TIME:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[16]=
		{
			["type"]=
			{
				["level3"]=9,
				["level1"]=4,
				["level4"]=75,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[2]=
				{
					[1]=0,
					[2]=28,
					[3]=2,
					[0]=1,
				},
				[3]=
				{
					[1]=25,
					[2]=22,
					[3]=26,
					[4]=20,
					[5]=15,
					[6]=18,
					[7]=23,
					[8]=17,
					[9]=27,
					[10]=24,
					[11]=14,
					[12]=21,
					[13]=19,
					[14]=16,
					[0]=13,
				},
				[6]=
				{
					[1]=5,
					[2]=10,
					[3]=1,
					[4]=7,
					[5]=9,
					[6]=11,
					[7]=3,
					[8]=8,
					[0]=0,
				},
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=21,
				[7]=22,
				[8]=2,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[2]=
				{
					[1]=0,
					[2]=27,
					[3]=2,
					[0]=1,
				},
				[3]=
				{
					[1]=24,
					[2]=21,
					[3]=25,
					[4]=19,
					[5]=14,
					[6]=17,
					[7]=22,
					[8]=16,
					[9]=26,
					[10]=23,
					[11]=13,
					[12]=20,
					[13]=18,
					[14]=15,
					[0]=12,
				},
				[11]=
				{
					[1]=38,
					[2]=36,
					[3]=39,
					[4]=34,
					[5]=30,
					[6]=33,
					[7]=2,
					[8]=32,
					[9]=3,
					[10]=37,
					[11]=29,
					[12]=35,
					[13]=1,
					[14]=31,
					[0]=28,
				},
				[6]=
				{
					[1]=7,
					[2]=3,
					[3]=5,
					[4]=9,
					[5]=11,
					[0]=1,
				},
				[12]=
				{
					[1]=0,
					[2]=28,
					[3]=6,
					[4]=44,
					[5]=31,
					[6]=43,
					[7]=29,
					[8]=45,
					[9]=42,
					[10]=30,
					[11]=32,
					[0]=40,
				},
			},
			["nose_fuzes_by_config"]=
			{
				[2]=
				{
					[1]=0,
					[2]=2,
					[3]=7,
					[0]=6,
				},
				[3]=
				{
					[1]=0,
					[2]=1,
					[3]=7,
					[0]=6,
				},
				[4]=
				{
					[1]=0,
					[2]=3,
					[3]=7,
					[0]=6,
				},
				[5]=
				{
					[0]=6,
				},
				[6]=
				{
					[0]=6,
				},
			},
			["tail_fuze_by_config_fuze"]=
			{
				[2]=
				{
					[2]=
					{
						[0]=2,
					},
				},
				[3]=
				{
					[3]=
					{
						[0]=1,
					},
				},
				[4]=
				{
					[4]=
					{
						[0]=3,
					},
				},
				[5]=
				{
					[5]=
					{
						[0]=3,
					},
				},
				[6]=
				{
					[6]=
					{
						[0]=2,
					},
				},
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=21,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES HD TOF:",
				},
				[2]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[3]=
				{
					["ParamType"]=17,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="CONFIG:",
				},
				[4]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
				[5]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[6]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[7]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[8]=
				{
					["ParamType"]=22,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES LD TOF:",
				},
				[9]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[10]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[11]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[17]=
		{
			["type"]=
			{
				["level3"]=49,
				["level1"]=4,
				["level4"]=76,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=14,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="SUU25 MNT:",
				},
				[2]=
				{
					["ParamType"]=13,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FF DIST:",
				},
				[0]=
				{
					["ParamType"]=14,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="H OVR TGT:",
				},
			},
		},
		[18]=
		{
			["type"]=
			{
				["level3"]=8,
				["level1"]=4,
				["level4"]=77,
				["level2"]=4,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
			},
		},
		[19]=
		{
			["type"]=
			{
				["level3"]=38,
				["level1"]=4,
				["level4"]=77,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=12,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="HOF:",
				},
				[2]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[3]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[4]=
				{
					["ParamType"]=11,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FUNC TIME:",
				},
				[5]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[6]=
				{
					["ParamType"]=10,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FZU39:",
				},
				[7]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[8]=
				{
					["ParamType"]=26,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="RPM:",
				},
				[9]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[10]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[11]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[20]=
		{
			["type"]=
			{
				["level3"]=38,
				["level1"]=4,
				["level4"]=78,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
				[4]=8,
				[5]=9,
				[6]=3,
				[7]=2,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=12,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="HOF:",
				},
				[2]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[3]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[4]=
				{
					["ParamType"]=11,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FUNC TIME:",
				},
				[5]=
				{
					["ParamType"]=9,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]=" RACK DEL:",
				},
				[6]=
				{
					["ParamType"]=10,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FZU39:",
				},
				[7]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[8]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[9]=
				{
					["ParamType"]=3,
					["Format"]="%.1f",
					["IsUnderline"]=1,
					["StringName"]="DES TOF:",
				},
				[10]=
				{
					["ParamType"]=8,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" EJECT VEL:",
				},
				[0]=
				{
					["ParamType"]=2,
					["Format"]="%s",
					["IsUnderline"]=1,
					["StringName"]="ESC MNVR:",
				},
			},
		},
		[21]=
		{
			["type"]=
			{
				["level3"]=49,
				["level1"]=4,
				["level4"]=80,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=14,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="SUU25 MNT:",
				},
				[2]=
				{
					["ParamType"]=13,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FF DIST:",
				},
				[0]=
				{
					["ParamType"]=14,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="H OVR TGT:",
				},
			},
		},
		[22]=
		{
			["type"]=
			{
				["level3"]=49,
				["level1"]=4,
				["level4"]=81,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=14,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="SUU25 MNT:",
				},
				[2]=
				{
					["ParamType"]=13,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FF DIST:",
				},
				[0]=
				{
					["ParamType"]=14,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="H OVR TGT:",
				},
			},
		},
		[23]=
		{
			["type"]=
			{
				["level3"]=36,
				["level1"]=4,
				["level4"]=85,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[7]=
				{
					[0]=29,
				},
			},
			["nose_fuzes"]=
			{
				[1]=0,
				[2]=1,
				[0]=7,
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[13]=
				{
					[1]=1,
					[2]=27,
					[3]=30,
					[4]=2,
					[0]=0,
				},
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
				[1]=
				{
					[1]=13,
					[0]=1,
				},
				[0]=
				{
					[1]=13,
					[0]=1,
				},
				[7]=
				{
					[0]=1,
				},
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[2]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[3]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
			},
		},
		[24]=
		{
			["type"]=
			{
				["level3"]=36,
				["level1"]=4,
				["level4"]=86,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
				[1]=
				{
					[1]=7,
					[2]=3,
					[3]=4,
					[4]=9,
					[5]=12,
					[0]=1,
				},
				[7]=
				{
					[0]=29,
				},
			},
			["nose_fuzes"]=
			{
				[1]=0,
				[2]=1,
				[0]=7,
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
				[1]=
				{
					[1]=6,
					[2]=3,
					[3]=4,
					[4]=8,
					[5]=11,
					[0]=1,
				},
				[13]=
				{
					[1]=1,
					[2]=27,
					[3]=30,
					[4]=2,
					[0]=0,
				},
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
				[1]=
				{
					[1]=13,
					[0]=1,
				},
				[0]=
				{
					[1]=13,
					[0]=1,
				},
				[7]=
				{
					[0]=1,
				},
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
				[2]=
				{
					["ParamType"]=4,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="N-",
				},
				[3]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=5,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="T-",
				},
			},
		},
		[25]=
		{
			["type"]=
			{
				["level3"]=38,
				["level1"]=4,
				["level4"]=87,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=12,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="HOF:",
				},
				[2]=
				{
					["ParamType"]=10,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FZU39:",
				},
				[3]=
				{
					["ParamType"]=11,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FUNC TIME:",
				},
				[4]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
			},
		},
		[26]=
		{
			["type"]=
			{
				["level3"]=38,
				["level1"]=4,
				["level4"]=88,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=12,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="HOF:",
				},
				[2]=
				{
					["ParamType"]=10,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FZU39:",
				},
				[3]=
				{
					["ParamType"]=11,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FUNC TIME:",
				},
				[4]=
				{
					["ParamType"]=26,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="RPM:",
				},
				[5]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
			},
		},
		[27]=
		{
			["type"]=
			{
				["level3"]=38,
				["level1"]=4,
				["level4"]=89,
				["level2"]=5,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=12,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="HOF:",
				},
				[2]=
				{
					["ParamType"]=10,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FZU39:",
				},
				[3]=
				{
					["ParamType"]=11,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="FUNC TIME:",
				},
				[4]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="BMB MNT:",
				},
			},
		},
		[28]=
		{
			["type"]=
			{
				["level3"]=8,
				["level1"]=4,
				["level4"]=138,
				["level2"]=4,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
			},
		},
		[29]=
		{
			["type"]=
			{
				["level3"]=8,
				["level1"]=4,
				["level4"]=139,
				["level2"]=4,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
			},
		},
		[30]=
		{
			["type"]=
			{
				["level3"]=101,
				["level1"]=4,
				["level4"]=140,
				["level2"]=4,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
			},
		},
		[31]=
		{
			["type"]=
			{
				["level3"]=101,
				["level1"]=4,
				["level4"]=141,
				["level2"]=4,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
			},
		},
		[32]=
		{
			["type"]=
			{
				["level3"]=101,
				["level1"]=4,
				["level4"]=142,
				["level2"]=4,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
			},
		},
		[33]=
		{
			["type"]=
			{
				["level3"]=33,
				["level1"]=4,
				["level4"]=144,
				["level2"]=7,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[2]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
				[3]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[4]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[0]=
				{
					["ParamType"]=23,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="POD SET:",
				},
			},
		},
		[34]=
		{
			["type"]=
			{
				["level3"]=33,
				["level1"]=4,
				["level4"]=145,
				["level2"]=7,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[2]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
				[3]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[4]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[0]=
				{
					["ParamType"]=23,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="POD SET:",
				},
			},
		},
		[35]=
		{
			["type"]=
			{
				["level3"]=33,
				["level1"]=4,
				["level4"]=146,
				["level2"]=7,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[2]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
				[3]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[4]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[0]=
				{
					["ParamType"]=23,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="POD SET:",
				},
			},
		},
		[36]=
		{
			["type"]=
			{
				["level3"]=33,
				["level1"]=4,
				["level4"]=147,
				["level2"]=7,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[2]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
				[3]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[4]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[0]=
				{
					["ParamType"]=23,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="POD SET:",
				},
			},
		},
		[37]=
		{
			["type"]=
			{
				["level3"]=33,
				["level1"]=4,
				["level4"]=148,
				["level2"]=7,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[2]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
				[3]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[4]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[0]=
				{
					["ParamType"]=23,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="POD SET:",
				},
			},
		},
		[38]=
		{
			["type"]=
			{
				["level3"]=33,
				["level1"]=4,
				["level4"]=149,
				["level2"]=7,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[2]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
				[3]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[4]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[0]=
				{
					["ParamType"]=23,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="POD SET:",
				},
			},
		},
		[39]=
		{
			["type"]=
			{
				["level3"]=33,
				["level1"]=4,
				["level4"]=150,
				["level2"]=7,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
				[2]=6,
				[3]=7,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[2]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
				[3]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[4]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[0]=
				{
					["ParamType"]=23,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="POD SET:",
				},
			},
		},
		[40]=
		{
			["type"]=
			{
				["level3"]=33,
				["level1"]=4,
				["level4"]=151,
				["level2"]=7,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=6,
				[2]=7,
				[3]=24,
				[4]=14,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=24,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]="DRAG:",
				},
				[2]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
				[3]=
				{
					["ParamType"]=14,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="H OVR TGT:",
				},
				[4]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[5]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[0]=
				{
					["ParamType"]=23,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="POD SET:",
				},
			},
		},
		[41]=
		{
			["type"]=
			{
				["level3"]=33,
				["level1"]=4,
				["level4"]=152,
				["level2"]=7,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=6,
				[2]=7,
				[3]=24,
				[4]=14,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=24,
					["Format"]="%.2f",
					["IsUnderline"]=1,
					["StringName"]="DRAG:",
				},
				[2]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
				[3]=
				{
					["ParamType"]=14,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="H OVR TGT:",
				},
				[4]=
				{
					["ParamType"]=6,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ RT:",
				},
				[5]=
				{
					["ParamType"]=7,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]=" ADJ UP:",
				},
				[0]=
				{
					["ParamType"]=23,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="POD SET:",
				},
			},
		},
		[42]=
		{
			["type"]=
			{
				["level3"]=101,
				["level1"]=4,
				["level4"]=154,
				["level2"]=4,
			},
			["nose_set_by_fuze"]=
			{
			},
			["nose_fuzes"]=
			{
			},
			["settings"]=
			{
				[1]=1,
			},
			["tail_set_by_fuze"]=
			{
			},
			["nose_fuzes_by_config"]=
			{
			},
			["tail_fuze_by_config_fuze"]=
			{
			},
			["tail_fuze_by_fuze"]=
			{
			},
			["strings"]=
			{
				[1]=
				{
					["ParamType"]=1,
					["Format"]="%d",
					["IsUnderline"]=1,
					["StringName"]="MIN ALT:",
				},
				[0]=
				{
					["ParamType"]=0,
					["Format"]="%s",
					["IsUnderline"]=0,
					["StringName"]="LAUNCHER:",
				},
			},
		},
	},
	["stores"]=
	{
		[1]=
		{
			["rocket"]=0,
			["misctypes"]=
			{
				["CTU2A"]=0,
				["TravelPod"]=1,
				["TK600"]=1,
			},
			["cbu"]=1,
			["cbutypes"]=
			{
				["CBU103"]=1,
				["CBU104"]=1,
				["CBU105"]=1,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=0,
				["GBU10"]=1,
				["GBU12"]=1,
				["GBU31"]=0,
			},
			["racktypes"]=
			{
				["LAU117"]=0,
				["LAU68"]=0,
				["LAU131"]=0,
				["TER"]=1,
				["SUU25"]=0,
				["LAU88"]=0,
				["LAU105"]=0,
			},
			["pod"]=0,
			["missile"]=0,
			["flare"]=0,
			["misc"]=1,
			["bombtypes"]=
			{
				["BLU52"]=1,
				["BDU33"]=1,
				["BDU56"]=1,
				["MK82A"]=1,
				["MK84"]=1,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
		[2]=
		{
			["rocket"]=1,
			["misctypes"]=
			{
				["CTU2A"]=0,
				["TravelPod"]=1,
				["TK600"]=1,
			},
			["cbu"]=1,
			["cbutypes"]=
			{
				["CBU103"]=1,
				["CBU104"]=1,
				["CBU105"]=1,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=1,
				["GBU10"]=1,
				["GBU12"]=1,
				["GBU31"]=1,
			},
			["racktypes"]=
			{
				["LAU117"]=0,
				["LAU68"]=1,
				["LAU131"]=1,
				["TER"]=1,
				["SUU25"]=0,
				["LAU88"]=0,
				["LAU105"]=0,
			},
			["pod"]=0,
			["missile"]=0,
			["flare"]=0,
			["misc"]=1,
			["bombtypes"]=
			{
				["BLU52"]=1,
				["BDU33"]=1,
				["BDU56"]=1,
				["MK82A"]=1,
				["MK84"]=1,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
		[3]=
		{
			["rocket"]=1,
			["misc"]=0,
			["cbu"]=1,
			["podtypes"]=
			{
				["ALQ184"]=0,
				["ALQ131"]=0,
				["LITENING"]=1,
			},
			["cbutypes"]=
			{
				["CBU103"]=0,
				["CBU104"]=0,
				["CBU105"]=0,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=0,
				["GBU10"]=0,
				["GBU12"]=1,
				["GBU31"]=0,
			},
			["racktypes"]=
			{
				["LAU117"]=0,
				["LAU68"]=1,
				["LAU131"]=1,
				["TER"]=0,
				["SUU25"]=1,
				["LAU88"]=0,
				["LAU105"]=0,
			},
			["pod"]=1,
			["missile"]=0,
			["flare"]=1,
			["bombtypes"]=
			{
				["BLU52"]=1,
				["BDU33"]=0,
				["BDU56"]=0,
				["MK82A"]=1,
				["MK84"]=0,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
		[4]=
		{
			["rocket"]=0,
			["misctypes"]=
			{
				["CTU2A"]=0,
				["TravelPod"]=1,
				["TK600"]=0,
			},
			["cbu"]=1,
			["cbutypes"]=
			{
				["CBU103"]=1,
				["CBU104"]=1,
				["CBU105"]=1,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=1,
				["GBU10"]=1,
				["GBU12"]=1,
				["GBU31"]=1,
			},
			["racktypes"]=
			{
				["LAU117"]=0,
				["LAU68"]=0,
				["LAU131"]=0,
				["TER"]=1,
				["SUU25"]=0,
				["LAU88"]=0,
				["LAU105"]=0,
			},
			["pod"]=0,
			["missile"]=0,
			["flare"]=0,
			["misc"]=1,
			["bombtypes"]=
			{
				["BLU52"]=1,
				["BDU33"]=1,
				["BDU56"]=1,
				["MK82A"]=1,
				["MK84"]=1,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
		[5]=
		{
			["rocket"]=0,
			["misc"]=0,
			["cbu"]=1,
			["podtypes"]=
			{
				["ALQ184"]=1,
				["ALQ131"]=1,
				["LITENING"]=0,
			},
			["cbutypes"]=
			{
				["CBU103"]=0,
				["CBU104"]=0,
				["CBU105"]=0,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=0,
				["GBU10"]=0,
				["GBU12"]=1,
				["GBU31"]=0,
			},
			["racktypes"]=
			{
				["LAU117"]=0,
				["LAU68"]=0,
				["LAU131"]=0,
				["TER"]=0,
				["SUU25"]=0,
				["LAU88"]=0,
				["LAU105"]=1,
			},
			["pod"]=1,
			["missiletypes"]=
			{
				["AIM9"]=1,
				["AGM65"]=0,
			},
			["missile"]=1,
			["flare"]=0,
			["bombtypes"]=
			{
				["BLU52"]=0,
				["BDU33"]=0,
				["BDU56"]=0,
				["MK82A"]=1,
				["MK84"]=0,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
		[6]=
		{
			["rocket"]=1,
			["misctypes"]=
			{
				["CTU2A"]=0,
				["TravelPod"]=1,
				["TK600"]=1,
			},
			["cbu"]=1,
			["cbutypes"]=
			{
				["CBU103"]=1,
				["CBU104"]=1,
				["CBU105"]=1,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=1,
				["GBU10"]=1,
				["GBU12"]=1,
				["GBU31"]=1,
			},
			["racktypes"]=
			{
				["LAU117"]=0,
				["LAU68"]=1,
				["LAU131"]=1,
				["TER"]=1,
				["SUU25"]=0,
				["LAU88"]=0,
				["LAU105"]=0,
			},
			["pod"]=0,
			["missile"]=0,
			["flare"]=0,
			["misc"]=1,
			["bombtypes"]=
			{
				["BLU52"]=1,
				["BDU33"]=1,
				["BDU56"]=1,
				["MK82A"]=1,
				["MK84"]=1,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
		[7]=
		{
			["rocket"]=1,
			["misctypes"]=
			{
				["CTU2A"]=1,
				["TravelPod"]=1,
				["TK600"]=0,
			},
			["cbu"]=1,
			["cbutypes"]=
			{
				["CBU103"]=1,
				["CBU104"]=1,
				["CBU105"]=1,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=1,
				["GBU10"]=1,
				["GBU12"]=1,
				["GBU31"]=1,
			},
			["racktypes"]=
			{
				["LAU117"]=1,
				["LAU68"]=1,
				["LAU131"]=1,
				["TER"]=1,
				["SUU25"]=1,
				["LAU88"]=1,
				["LAU105"]=0,
			},
			["pod"]=0,
			["missiletypes"]=
			{
				["AIM9"]=0,
				["AGM65"]=1,
			},
			["missile"]=1,
			["flare"]=1,
			["misc"]=1,
			["bombtypes"]=
			{
				["BLU52"]=1,
				["BDU33"]=1,
				["BDU56"]=1,
				["MK82A"]=1,
				["MK84"]=1,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
		[8]=
		{
			["rocket"]=0,
			["misctypes"]=
			{
				["CTU2A"]=0,
				["TravelPod"]=1,
				["TK600"]=0,
			},
			["cbu"]=1,
			["cbutypes"]=
			{
				["CBU103"]=1,
				["CBU104"]=1,
				["CBU105"]=1,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=1,
				["GBU10"]=1,
				["GBU12"]=1,
				["GBU31"]=1,
			},
			["racktypes"]=
			{
				["LAU117"]=0,
				["LAU68"]=0,
				["LAU131"]=0,
				["TER"]=1,
				["SUU25"]=0,
				["LAU88"]=0,
				["LAU105"]=0,
			},
			["pod"]=0,
			["missile"]=0,
			["flare"]=0,
			["misc"]=1,
			["bombtypes"]=
			{
				["BLU52"]=1,
				["BDU33"]=1,
				["BDU56"]=1,
				["MK82A"]=1,
				["MK84"]=1,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
		[9]=
		{
			["rocket"]=1,
			["misctypes"]=
			{
				["CTU2A"]=1,
				["TravelPod"]=1,
				["TK600"]=0,
			},
			["cbu"]=1,
			["cbutypes"]=
			{
				["CBU103"]=1,
				["CBU104"]=1,
				["CBU105"]=1,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=1,
				["GBU10"]=1,
				["GBU12"]=1,
				["GBU31"]=1,
			},
			["racktypes"]=
			{
				["LAU117"]=1,
				["LAU68"]=1,
				["LAU131"]=1,
				["TER"]=1,
				["SUU25"]=1,
				["LAU88"]=1,
				["LAU105"]=0,
			},
			["pod"]=0,
			["missiletypes"]=
			{
				["AIM9"]=0,
				["AGM65"]=1,
			},
			["missile"]=1,
			["flare"]=1,
			["misc"]=1,
			["bombtypes"]=
			{
				["BLU52"]=1,
				["BDU33"]=1,
				["BDU56"]=1,
				["MK82A"]=1,
				["MK84"]=1,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
		[10]=
		{
			["rocket"]=1,
			["misc"]=0,
			["cbu"]=1,
			["podtypes"]=
			{
				["ALQ184"]=0,
				["ALQ131"]=0,
				["LITENING"]=1,
			},
			["cbutypes"]=
			{
				["CBU103"]=0,
				["CBU104"]=0,
				["CBU105"]=0,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=0,
				["GBU10"]=0,
				["GBU12"]=1,
				["GBU31"]=0,
			},
			["racktypes"]=
			{
				["LAU117"]=0,
				["LAU68"]=1,
				["LAU131"]=1,
				["TER"]=0,
				["SUU25"]=1,
				["LAU88"]=0,
				["LAU105"]=0,
			},
			["pod"]=1,
			["missile"]=0,
			["flare"]=1,
			["bombtypes"]=
			{
				["BLU52"]=1,
				["BDU33"]=0,
				["BDU56"]=0,
				["MK82A"]=1,
				["MK84"]=0,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
		[0]=
		{
			["rocket"]=0,
			["misc"]=0,
			["cbu"]=1,
			["podtypes"]=
			{
				["ALQ184"]=1,
				["ALQ131"]=1,
				["LITENING"]=0,
			},
			["cbutypes"]=
			{
				["CBU103"]=0,
				["CBU104"]=0,
				["CBU105"]=0,
				["CBU97"]=1,
				["CBU89"]=1,
				["CBU87"]=1,
			},
			["bomb"]=1,
			["gbu"]=1,
			["rack"]=1,
			["gbutypes"]=
			{
				["GBU38"]=0,
				["GBU10"]=0,
				["GBU12"]=1,
				["GBU31"]=0,
			},
			["racktypes"]=
			{
				["LAU117"]=0,
				["LAU68"]=0,
				["LAU131"]=0,
				["TER"]=0,
				["SUU25"]=0,
				["LAU88"]=0,
				["LAU105"]=1,
			},
			["pod"]=1,
			["missiletypes"]=
			{
				["AIM9"]=1,
				["AGM65"]=0,
			},
			["missile"]=1,
			["flare"]=0,
			["bombtypes"]=
			{
				["BLU52"]=0,
				["BDU33"]=0,
				["BDU56"]=0,
				["MK82A"]=1,
				["MK84"]=0,
				["BDU50"]=1,
				["MK82"]=1,
			},
		},
	},
	["InventoryTraining"]=
	{
		[1]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=2,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[2]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=3,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[3]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=4,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[4]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=5,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[5]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=6,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[6]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=7,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[7]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=8,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[8]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=9,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[9]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=10,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[10]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=11,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[0]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=1,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
	},
	["InventoryReal"]=
	{
		[1]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=2,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[2]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=3,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[3]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=4,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[4]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=5,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[5]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=6,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[6]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=7,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[7]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=8,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[8]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=9,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[9]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=10,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[10]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=11,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
		[0]=
		{
			["ff_dist"]=500,
			["WpnName"]="",
			["IsHung"]=0,
			["StationNumber"]=1,
			["ALQ131Type"]=0,
			["IsInventoryError"]=0,
			["RocketPylon"]=0,
			["IsProfileMissing"]=0,
			["Ignition"]=0,
			["Rpm"]=3,
			["NoseFuzeType"]=0,
			["TailSet"]=0,
			["Eject"]=0,
			["LauncherCount"]=1,
			["TailFuzeType"]=1,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["LsrCode"]=1688,
			["LauncherName"]="PYLON",
			["NoseSet"]=0,
			["PodSet"]=0,
			["RocketMotor"]=0,
			["Launcher"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["ALQ184Type"]=1,
			["FuncTime"]=5,
			["Fzu39"]=0,
			["Config"]=4,
			["IsMaverick"]=0,
			["series"]=4,
			["Count"]=0,
			["hof"]=6,
		},
	},
	["profiles"]=
	{
		["WPNS OFF"]=
		{
			["HeightOverTarget"]=0,
			["MinAlt"]=0,
			["index"]=0,
			["DesTOF"]=0,
			["Drag"]=0,
			["HUD_RotaryStatus"]=0,
			["ReleaseMode"]=0,
			["ImpAng"]=45,
			["AdjRt"]=0,
			["RackDel"]=0,
			["MinTOF"]=0,
			["PattAz"]=0,
			["AutoLs"]=821141744,
			["Type"]=
			{
				["level3"]=0,
				["level1"]=0,
				["level4"]=0,
				["level2"]=0,
			},
			["IAM_target_id"]="9999",
			["LsTime"]=0,
			["Qty"]=1,
			["ModeCCIP_RP"]=0,
			["Soln"]=1,
			["Feet"]=75,
			["FuzeType"]=0,
			["Config"]=4,
			["EscMnvr"]=0,
			["AdjUp"]=0,
			["DesHD_TOF"]=0,
			["DesLD_TOF"]=0,
			["EjectVel"]=0,
			["ImpAz"]=45,
		},
	},
}
